Add Latch data source
latchbio/flaightkit pull request #8
Opened 2022-01-15 19:35 UTC by AidanAbd

# TL;DR
_Please replace this text with a description of what this PR accomplishes._

## Type
 - [ ] Bug Fix
 - [ ] Feature
 - [ ] Plugin

## Are all requirements met?

 - [ ] Code completed
 - [ ] Smoke tested
 - [ ] Unit tests added
 - [ ] Code documentation added
 - [ ] Any pending items have an associated Issue

## Complete description
 _How did you fix the bug, make the feature etc. Link to any design docs etc_

## Tracking Issue
https://github.com/lyft/flyte/issues/<number>

## Follow-up issue
_NA_
OR
_https://github.com/lyft/flyte/issues/<number>_

2022-02-09 17:27 UTC, AidanAbd commented on flytekit/interfaces/data/latch/latch_proxy.py
> +                raise _FlyteUserException("failed to upload part `{}` of file `{}`".format(key, file_path))
Already does in the outer data api

2022-02-09 18:09 UTC, AidanAbd commented on flytekit/interfaces/data/latch/latch_proxy.py
> +        path = path[len("latch://") :]
done

2022-02-11 17:54 UTC, maximsmol requested changes

2022-02-11 17:54 UTC, maximsmol commented on flytekit/interfaces/data/latch/latch_proxy.py
> +            raise ValueError("not a Latch URL. Please use URL of the format latch:///...")
```suggestion
            raise ValueError(f"expected a Latch URL (latch:///...): {remote_path}")
```

2022-02-11 17:54 UTC, maximsmol commented on flytekit/interfaces/data/latch/latch_proxy.py
> +            raise ValueError("not a Latch URL. Please use URL of the format latch:///...")
likewise elsewhere

2022-02-11 17:54 UTC, maximsmol commented on flytekit/interfaces/data/latch/latch_proxy.py
> +        :param Text local_path:
```suggestion
        :param str local_path:
```

likewise elsewhere

2022-02-15 18:38 UTC, AidanAbd commented on flytekit/interfaces/data/latch/latch_proxy.py
> +        :param Text local_path:
done

2022-02-16 00:58 UTC, merged